name: Daily Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:       # Allows manual trigger from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests selenium webdriver-manager

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i chrome.deb || sudo apt-get -f install -y
        google-chrome --version

    - name: Run main scraper
      run: python main_scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'dwaynedibbli'
        git config --global user.email 'geoffknight83@gmail.com'
        git add index.html
        git commit -m "Daily update of free games list" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
