name: Hourly Scrape

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests beautifulsoup4 selenium webdriver-manager

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run main scraper with Xvfb
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' python main_scraper.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add index.html game_pages/
          git commit -m "Hourly update of free games list" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
