name: Hourly Scrape

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Install Chrome or Chromium
        sudo apt-get install -y google-chrome-stable
        # If google-chrome-stable is not found, use chromium-browser
        # sudo apt-get install -y chromium-browser
        # Xvfb for headless display (if needed)
        sudo apt-get install -y xvfb
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 requests

    - name: Run main scraper with Xvfb
      run: |
        # Option A: Just run python if you’re using normal headless flags
        # python main_scraper.py
        
        # Option B: If you still have issues, try forcing an X display:
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' python main_scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'YourUsername'
        git config --global user.email 'YourEmail@example.com'
        git add index.html
        git commit -m "Hourly update of free games list" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
