name: Daily Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:       # Allows manual trigger from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run scraper
      run: python scraper.py

    - name: Check for changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'you@example.com'
        git add index.html || true
        git diff --quiet || git commit -m "Daily update of free games list"

    - name: Push changes if there are any
      if: success()
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
